# House Pricing data module

In [1]:
import os
from pathlib import Path

p = Path.cwd()
os.chdir(p.parent)
os.getcwd()

'/root/repos/lightning/HousePricing'

In [4]:
from src.data import HousePricingDataModule

housing = HousePricingDataModule(validation_size=0.1)
housing.prepare_data()

[INFO]: Skipping downloading data. Data is already downloaded
[INFO]: Reloading set up data...


In [5]:
for stage in ["fit", "test", "predict"]:
    housing.setup(stage=stage)

for batch in housing.train_dataloader():
    break

for batch in housing.val_dataloader():
    break

for batch in housing.test_dataloader():
    break

for batch in housing.predict_dataloader():
    break

[INFO]: Setting up fit dataset/s
[INFO]: Train dataset size: 1166
[INFO]: Validation dataset size: 129
[INFO]: Setting up test dataset/s
[INFO]: Setting up predict dataset/s
[INFO]: Train dataloader size: 37
[INFO]: Validation dataloader size: 2
[INFO]: Test dataloader size: 2
[INFO]: Predict dataloader size: 12


In [6]:
for batch in housing.test_dataloader():
    print(batch.keys())
    print(batch["id"][:3])
    print(batch["target"][:3])
    print(batch["inputs"][:3])
    break

[INFO]: Test dataloader size: 2
dict_keys(['id', 'inputs', 'target'])
tensor([ 893, 1106,  414], dtype=torch.int32)
tensor([154500., 325000., 115000.])
tensor([[0.0000, 0.1678, 0.0333, 0.5556, 0.8571, 0.6594, 0.8833, 0.0000, 0.2934,
         0.0000, 0.1695, 0.3309, 0.2536, 0.0000, 0.0000, 0.1690, 0.0000, 0.5000,
         0.3333, 0.0000, 0.3750, 0.3333, 0.3333, 0.0000, 0.5727, 0.2500, 0.1947,
         0.2240, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0909, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.000

In [7]:
for batch in housing.predict_dataloader():
    print(batch.keys())
    print(batch["id"][:3])
    print(batch["inputs"][:3])
    break

[INFO]: Predict dataloader size: 12
dict_keys(['id', 'inputs'])
tensor([1461, 1462, 1463], dtype=torch.int32)
tensor([[0.0000, 0.2021, 0.0482, 0.4444, 0.5714, 0.6449, 0.1833, 0.0000, 0.2071,
         0.1278, 0.1156, 0.2756, 0.1942, 0.0000, 0.0000, 0.1294, 0.0000, 0.0000,
         0.3333, 0.0000, 0.2500, 0.3333, 0.2500, 0.0000, 0.5545, 0.2500, 0.5383,
         0.1634, 0.0000, 0.0000, 0.0000, 0.2500, 0.0000, 0.0000, 0.4545, 1.0000,
         0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 1.0000, 0.0000,